# Generated by Django 4.0 on 2021-12-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitv',
            name='times',
            field=models.CharField(default=6000, max_length=255),
        ),
    ]
