# Generated by Django 4.0 on 2021-12-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_visitv_times'),
    ]

    operations = [
        migrations.CreateModel(
            name='infor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=6000, max_length=255)),
                ('name', models.CharField(default=6000, max_length=255)),
                ('visittime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
