# Generated by Django 4.0 on 2021-12-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_infor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='name',
            field=models.CharField(db_collation='utf8_general_ci', default=6000, max_length=255),
        ),
    ]
