# Generated by Django 4.0 on 2021-12-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_alter_infor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='visttimes',
            field=models.CharField(default=100, max_length=255),
        ),
    ]
