# Generated by Django 4.0 on 2021-12-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0005_infor_visttimes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infor',
            old_name='visittime',
            new_name='visit_time',
        ),
        migrations.RenameField(
            model_name='infor',
            old_name='visttimes',
            new_name='visit_times',
        ),
    ]
