# Generated by Django 4.0 on 2021-12-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0006_rename_visittime_infor_visit_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='visit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
