# Generated by Django 4.0 on 2021-12-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0009_alter_infor_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='address',
            field=models.CharField(default='中国，北京', max_length=255),
        ),
        migrations.AddField(
            model_name='infor',
            name='position',
            field=models.CharField(default='(0,0)', max_length=255),
        ),
    ]
