# Generated by Django 4.0 on 2021-12-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0010_infor_address_infor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='address',
            field=models.CharField(db_collation='utf8_general_ci', default='中国，北京', max_length=255),
        ),
        migrations.AlterField(
            model_name='infor',
            name='position',
            field=models.CharField(db_collation='utf8_general_ci', default='(0,0)', max_length=255),
        ),
    ]
