# Generated by Django 4.0 on 2021-12-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0012_alter_infor_address_alter_infor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='address',
            field=models.CharField(db_collation='utf8_general_ci', default='-', max_length=255),
        ),
        migrations.AlterField(
            model_name='infor',
            name='position',
            field=models.CharField(db_collation='utf8_general_ci', default='-', max_length=255),
        ),
    ]
