# Generated by Django 4.0 on 2021-12-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0014_alter_infor_address_alter_infor_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infor',
            name='address',
            field=models.CharField(default=6000, max_length=255),
        ),
        migrations.AlterField(
            model_name='infor',
            name='position',
            field=models.CharField(default=6000, max_length=255),
        ),
    ]
