# Generated by Django 4.0 on 2021-12-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0015_alter_infor_address_alter_infor_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitv',
            name='isclose',
            field=models.CharField(default=1, max_length=255),
        ),
    ]
