# Generated by Django 4.0 on 2021-12-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0016_visitv_isclose'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='islogin',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
