# Generated by Django 4.0 on 2021-12-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0017_infor_islogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default=10, max_length=255)),
                ('music', models.CharField(max_length=255)),
            ],
        ),
    ]
