# Generated by Django 4.0 on 2021-12-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0018_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='ip',
        ),
    ]
