# Generated by Django 4.0 on 2021-12-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0019_remove_music_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitv',
            name='oldtimes',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
